Vagrant.configure("2") do |config|

  config.vm.box = "b2-tp2-centos"

  config.vbguest.auto_update = false

  config.vm.box_check_update = false 

  config.vm.synced_folder ".", "/vagrant", disabled: true
  
  config.vm.define "tp3" do |tp3|
    tp3.vm.hostname = "tp3.b2"
    tp3.vm.define "tp3_b2"
    tp3.vm.network "public_network", ip: "192.168.1.12"
    tp3.vm.network "private_network", type: "dhcp"
    tp3.vm.provider "virtualbox" do |vb|
      vb.name = "tp3_b2"
      vb.memory = "2048"
    end
  end
end
