Vagrant.configure("2")do|config|
  config.vm.box="b2-tp4-centos"

  config.vbguest.auto_update = false

  config.vm.box_check_update = false 

  config.vm.synced_folder ".", "/vagrant", disabled: true

  # Config une première VM "gitea"
  config.vm.define "gitea" do |gitea|
    gitea.vm.network "private_network", ip: "192.168.2.21"
    gitea.vm.network "public_network", ip: "192.168.1.11"
    gitea.vm.hostname = "stack.gitea"
    gitea.vm.define "gitea"
    gitea.vm.provision "shell", path: "bootscript/gitea.sh"
    gitea.vm.provider "virtualbox" do |vb|
      vb.name = "gitea_tp4"
      vb.memory = "1024"
    end
  end

  # Config une VM "mariadb"
  config.vm.define "mariadb" do |mariadb|
    mariadb.vm.network "private_network", ip: "192.168.2.22"
    mariadb.vm.network "public_network", ip: "192.168.1.12"
    mariadb.vm.hostname = "stack.mariadb"
    mariadb.vm.define "mariadb"
    mariadb.vm.provision "shell", path: "bootscript/mariadb.sh"
    mariadb.vm.provider "virtualbox" do |vb|
      vb.name = "mariadb_tp4"
      vb.memory = "1024"
    end
  end

  # Config une VM "nginx"
  config.vm.define "nginx" do |nginx|
    nginx.vm.network "private_network", ip: "192.168.2.23"
    nginx.vm.network "public_network", ip: "192.168.1.13"
    nginx.vm.hostname = "stack.nginx"
    nginx.vm.define "nginx"
    nginx.vm.provision "shell", path: "bootscript/nginx.sh"
    nginx.vm.provider "virtualbox" do |vb|
      vb.name = "nginx_tp4"
      vb.memory = "1024"
    end
  end

  # Config une VM "nfs"
  config.vm.define "nfs" do |nfs|
    nfs.vm.network "private_network", ip: "192.168.2.24"
    nfs.vm.network "public_network", ip: "192.168.1.14"
    nfs.vm.hostname = "stack.nfs"
    nfs.vm.define "nfs"
    nfs.vm.provider "virtualbox" do |vb|
      vb.name = "nfs_tp4"
      vb.memory = "1024"
    end
  end

end